name: wnw11

on: push

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Install tools
      run: |
           Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -OutFile autoit-v3-setup.exe
           ./autoit-v3-setup.exe /S
           Start-Sleep -s 10
           Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe -OutFile SciTE4AutoIt3.exe
           ./SciTE4AutoIt3.exe /S
           Start-Sleep -s 10
           Invoke-WebRequest -Uri https://www.autoitscript.com/autoit3/scite/download/Au3Stripper.zip -OutFile Au3Stripper.zip
           Expand-Archive -Path Au3Stripper.zip -DestinationPath "C:\Program Files (x86)\AutoIt3\SciTE\au3Stripper" -Force

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Compile
      run: |
           dir
           C:\"Program Files (x86)"\AutoIt3\AutoIt3.exe "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3" /NoStatus /prod /in ".\WhyNotWin11.au3"
           Start-Sleep -s 10
           sha256sum -b WhyNotWin*.exe > checksum.sha256

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
       name: WNW11
       path: |
             WhyNotWin11.exe
             WhyNotWin11_x86.exe
             checksum.sha256
       if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
               WhyNotWin11.exe
               WhyNotWin11_x86.exe
               checksum.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
